# Generated by Django 4.2.7 on 2023-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='post/static/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pictur2',
            field=models.ImageField(blank=True, upload_to='post/static/images/'),
        ),
    ]
